name: Build, Test & Publish

on:
  push:
    branches: [ master ]

env:
  ASOFT_MAVEN_PGP_PRIVATE_KEY: ${{ secrets.ASOFT_MAVEN_PGP_PRIVATE_KEY }}
  ASOFT_MAVEN_PGP_PASSWORD: ${{ secrets.ASOFT_MAVEN_PGP_PASSWORD }}
  ASOFT_NEXUS_PASSWORD: ${{ secrets.ASOFT_NEXUS_PASSWORD }}
  ASOFT_NEXUS_USERNAME: ${{ secrets.ASOFT_NEXUS_USERNAME }}

jobs:
   deploy-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Making gradlew executable
        run: chmod +x ./gradlew
        working-directory: .
      - name: publishing persit-core
        run: ./gradlew :persist-core:publish
        working-directory: .
      - name: publishing persit-inmemory
        run: ./gradlew :persist-inmemory:publish
        working-directory: .
      - name: publishing persist-local
        run: ./gradlew :persist-local:publish
        working-directory: .
      - name: publishing persist-mongo
        run: ./gradlew :persist-mongo:publish
        working-directory: .
      - name: Closing and Releasing Repositories
        run: ./gradlew :persist-core:closeAndReleaseRepository
        working-directory: .
